### PR TITLE
Update pom property jenkins-openshift.version to va743a38

### PR DESCRIPTION
**Pull request by fabric8cd**

### CODE REVIEW

**Comment by fabric8cd** [comment]
[merge]

**Comment by fabric8cd** [comment]
snapshot YAML now available: `JENKINS_VERSION=veb05114-SNAPSHOT` `YAML_MVN_REPO=http://nexus.cd.k8s.fabric8.io/content/repositories/snapshots`

**Comment by fabric8cd** [comment]
snapshot YAML now available: `JENKINS_VERSION=veb05114-SNAPSHOT` `YAML_MVN_REPO=http://nexus.cd.k8s.fabric8.io/content/repositories/snapshots`

**Comment by fabric8cd** [comment]
snapshot YAML now available: `JENKINS_VERSION=veb05114-SNAPSHOT` `YAML_MVN_REPO=http://nexus.cd.k8s.fabric8.io/content/repositories/snapshots`

**Comment by rawlingsj** [comment]
closing as another PR is coming from openshift-jenkins-s2i-config

**Pull request closed without merging**
