### PR TITLE
changing the caddy version to the latest version

### PR DESCRIPTION
**Pull request by rupalibehera**
Updating the caddy server version, which includes fixes regarding license in https://registry.centos.org/repo/caddyserver/caddyserver,
Ref: HK1340

### CODE REVIEW

**Comment by fabric8cd** [comment]
PR now available for testing: Launch in [OpenShift.io](https://openshift.io/_profile/_tenant?jenkinsVersion=PR-v50ade17-1&mavenRepo=https://nexus.cd.test.fabric8.io/content/repositories/staging) and click the update tenant button

**Comment by fabric8cd** [comment]
PR now available for testing: Launch in [OpenShift.io](https://openshift.io/_profile/_tenant?jenkinsVersion=PR-v1b8b0f4-2&mavenRepo=https://nexus.cd.test.fabric8.io/content/repositories/staging) and click the update tenant button

**Comment by fabric8cd** [comment]
PR now available for testing: Launch in [OpenShift.io](https://openshift.io/_profile/_tenant?jenkinsVersion=PR-v5c9d751-3&mavenRepo=https://nexus.cd.test.fabric8.io/content/repositories/staging) and click the update tenant button

**Comment by rupalibehera** [comment]
The image is tested well, whenever we are ready to take this change we should just merge this.

**Comment by rupalibehera** [comment]
@pbergene let us when you want this in we can just merge this PR

**Comment by pbergene** [comment]
Thanks for looping me in, but I no need for me gatekeeping this :) 
If there's no reason to not merge then I'd say keep moving forward.

**Pull request merged**
