### PR TITLE
fixes Jenkins slave maven mirror

### PR DESCRIPTION
**Pull request by hrishin**
- added defined (http://repo1.maven.org/maven2/.meta/repository-metadata.xml) maven repository to download dependencies and plugins

### CODE REVIEW

**Comment by hrishin** [comment]
Fix for https://github.com/openshiftio/openshift.io/issues/2457

**Comment by chmouel** [comment]
@hrishin can you run numbers between before and after with this PR, please? So then I can quickly merge it ?

**Comment by hrishin** [comment]
@chmouel I have tested this on us-east-2 for a [springboot-booster](https://github.com/hrishin/maven-test) application.

_Before:_
Jenkins build : 14 min 11s
maven build  : 11:04 min
https://jenkins.openshift.io/job/hrishin/job/maven-test/job/master/3/console

_After:_
Jenkins build : 4min 09s 
maven build  : 03:04 min
https://jenkins.openshift.io/job/hrishin/job/maven-test/job/master/1/console

I'm not able to test it on us-east-2a cluster as my OSIO account is not provisioned yet.

cc: @kbsingh

**Comment by chmouel** [comment]
This is great numbers! 

@jfchevrette @kbsingh if you are okay with this (not having tested on -2a cluster) then I can merge this

**Comment by jaseemabid** [comment]
Great numbers @hrishin! LGTM.

**Comment by jaseemabid** [comment]
@hrishin I tried to diff the XMLs and its hard to understand the output. If you
add a block of config, please try to add that to the commit message. I'd go with
something as follows.

```
Use a good standard maven mirror instead of the default

The gist of the patch is to replace the first block with the next.

<profile>
    <id>nexus</id>
    <properties>
        <altDeploymentRepository>local-nexus::default::http://content-repository/content/repositories/staging/</altDeploymentRepository>
        <altReleaseDeploymentRepository>local-nexus::default::http://content-repository/content/repositories/staging/</altReleaseDeploymentRepository>
        <altSnapshotDeploymentRepository>local-nexus::default::http://content-repository/content/repositories/snapshots/</altSnapshotDeploymentRepository>
    </properties>
</profile>

<profile>
    <id>nexus</id>
    <properties>
        <altDeploymentRepository>local-nexus::default::http://content-repository/content/repositories/staging/</altDeploymentRepository>
        <altReleaseDeploymentRepository>local-nexus::default::http://content-repository/content/repositories/staging/</altReleaseDeploymentRepository>
        <altSnapshotDeploymentRepository>local-nexus::default::http://content-repository/content/repositories/snapshots/</altSnapshotDeploymentRepository>
    </properties>
    <repositories>
        <repository>
            <id>central</id>
            <url>https://repo1.maven.org/maven2</url>
            <releases>
                <enabled>true</enabled>
            </releases>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>central</id>
            <url>https://repo1.maven.org/maven2</url>
            <releases>
                <enabled>true</enabled>
            </releases>
        </pluginRepository>
    </pluginRepositories>
</profile>

```

For the future version of ourselves :D

**Comment by chmouel** [comment]
as per MM discussion, let's wait to sync with @jfchevrette before merging this,

**Comment by kbsingh** [comment]
:+1: from my side, testing on 2a is going to need to wait a day or so ( note email around 2a being in maintenence for storage till end of day today ). Based on the work we had done to recommend this setting change, I would say we are good to merge and promote.

**Comment by fabric8cd** [comment]
PR now available for testing: Launch in [OpenShift.io](https://openshift.io/_profile/_tenant?jenkinsVersion=PR-vce0603c-2&mavenRepo=https://nexus.cd.test.fabric8.io/content/repositories/staging) and click the update tenant button

**Comment by kbsingh** [comment]
@hrishin @jaseemabid @chmouel what are we waiting on to push this change ? looks like no movement for a critical issue in 6 days ?

**Comment by hrishin** [comment]
Merging this PR. We were waiting for @jfchevrette review.

**Pull request merged**
