### PR TITLE
Maven settings changed

### PR DESCRIPTION
**Pull request by hrishin**
- Changed maven local repository file location from /root/.mvnrepository to default

@rupalibehera @jaseemabid @sthaha @chmouel

### CODE REVIEW

**Comment by jaseemabid** [comment]
@hrishin My patch does the same, but I've been unable to start a build and test it.

**Comment by jaseemabid** [comment]
Ah! Now I know why grepping for this never worked. Damn!

I see another volume mounted at the same path. 

```
volumes: [secretVolume(secretName: 'jenkins-maven-settings', mountPath: '/root/.m2'),
```

**Comment by fabric8cd** [comment]
PR now available for testing: Launch in [OpenShift.io](https://openshift.io/_profile/_tenant?jenkinsVersion=PR-v52e9dd8-1&mavenRepo=https://nexus.cd.test.fabric8.io/content/repositories/staging) and click the update tenant button

**Comment by fabric8cd** [comment]
PR now available for testing: Launch in [OpenShift.io](https://openshift.io/_profile/_tenant?jenkinsVersion=PR-v871ae64-2&mavenRepo=https://nexus.cd.test.fabric8.io/content/repositories/staging) and click the update tenant button

**Comment by jaseemabid** [comment]
@hrishin  Since we are changing permissions in the image, shall we close this PR?

**Pull request closed without merging**
