### PR TITLE
fix maven settings to use better repository mirror

### PR DESCRIPTION
**Pull request by hrishin**
Due to wrong maven repo URL, sometimes maven command is failing to download
dependencies. Hence it's failing the build sporadically.
This patch updates the maven settings to use a right repository for downloading dependencies and plugins.

Fixes https://github.com/openshiftio/openshift.io/issues/3796

### CODE REVIEW

**Comment by fabric8cd** [comment]
PR now available for testing: Launch in [OpenShift.io](https://openshift.io/_profile/_tenant?jenkinsVersion=PR-v1fc2412-1&mavenRepo=https://nexus.cd.test.fabric8.io/content/repositories/staging) and click the update tenant button

**Comment by fabric8cd** [comment]
PR now available for testing: Launch in [OpenShift.io](https://openshift.io/_profile/_tenant?jenkinsVersion=PR-v80e5cd9-3&mavenRepo=https://nexus.cd.test.fabric8.io/content/repositories/staging) and click the update tenant button

**Comment by hrishin** [comment]
@sthaha @rupalibehera @kishansagathiya @piyush1594 could you please review it?

**Comment by hrishin** [comment]
Thanks, @sthaha @piyush1594

**Pull request merged**
