### PR TITLE
Remove user's edit role to lock jenkins namespace

### PR DESCRIPTION
**Pull request by sthaha**
Previously users were given the permission to make changes to the
jenkins namespace which means they could potentially break jenkins.
This patch addresses the [issue 1900] by removing user's `edit` role.

[issue 1900]: https://github.com/openshiftio/openshift.io/issues/1900

### CODE REVIEW

**Comment by fabric8cd** [comment]
PR now available for testing: Launch in [OpenShift.io](https://openshift.io/_profile/_tenant?jenkinsVersion=PR-v106f640-1&mavenRepo=https://nexus.cd.test.fabric8.io/content/repositories/staging) and click the update tenant button

**Comment by rupalibehera** [comment]
@aslakknutsen , We would appreciate your review here to help @sthaha merge this PR, thanks!

**Comment by aslakknutsen** [comment]
Just to note: This PR was tested and cause Promote to fail. Looking at a different solution.

**Comment by fabric8cd** [comment]
PR now available for testing: Launch in [OpenShift.io](https://openshift.io/_profile/_tenant?jenkinsVersion=PR-vbd9a013-2&mavenRepo=https://nexus.cd.test.fabric8.io/content/repositories/staging) and click the update tenant button

**Comment by sthaha** [comment]
@aslakknutsen  I am a bit lost here, is this what you meant by `roleRef` to `view` ? Applying the patch removes the `edit` rolebinding and jenkins fails to promote to Prod. 

On a related note, in order to promote to prod, shouldn't Jenkins actually check if the user has `edit` on the `target` namespace instead of the `jenkins` namespace?

**Comment by aslakknutsen** [comment]
@sthaha Yes, this patch looks correct based on what was said in 'some email thread' a long time ago. But maybe it was miss understood or has changed since.

@sthaha And yes, I agree. It should be the edit rights on the target that should matter. Not sure if Jenkins has dynamic enough roles for that.

**Comment by fabric8cd** [comment]
PR now available for testing: Launch in [OpenShift.io](https://openshift.io/_profile/_tenant?jenkinsVersion=PR-v77ef537-3&mavenRepo=https://nexus.cd.test.fabric8.io/content/repositories/staging) and click the update tenant button

**Pull request merged**
